### ISSUE TITLE
Need help understanding how best to utilize this

### ISSUE THREAD

**Issue by cmalven** [putyourlightson/craft-blitz-netlify#1]
The idea of this integration is amazing. That being said, I'm having a hard time wrapping my head around exactly what this does and how best to integrate it with a typical Craft site.

I have my site deploying successfully to Netlify, but I immediately run into a few challenges/questions:

- This integration seems to only deploy the static cached template files that it has generated. Any suggestions for how to deploy all of the other files – CSS, JS, images, etc – needed by the site?
- Since Blitz is operating on its own server, all of the URLs it generates, caches, and deploys are based on the `siteUrl` for that Craft install. But the Netlify domain won't be the same, so I'm not sure how URLs are supposed to continue to work once deployed to Netlify.
- I currently use [Asset Rev](https://github.com/clubstudioltd/craft-asset-rev) for revving static files (CSS + JS). But since Blitz isn't deploying the revved CSS + JS files that are on the main Craft server, or the `manifest.json` that contains the information for them, there's no obvious way to ensure that Netlify will include the files that the cached Blitz templates point to. This one isn't really Blitz's problem but it is a pain point.
- During development, it isn't really an issue that my Craft install is at `https://foo.com` and Netlify deploy is at `https://foo.netlify.com`, but what is the recommended setup for this in production? Would you suggest a setup like `https://admin.foo.com` for Craft and `https://foo.com` for the Netlify deployment?

I might be entirely missing the point of this integration, and it isn't at all intended to result in a working production site without significant additional effort. Totally reasonable if that's the case, but it might be helpful to hint at that in the documentation.

**Comment by bencroker** [comment]
Hi Chris, thanks for posting this issue. All of your questions are completely valid and I am in the process of writing a tutorial that explains all of this (and more). However, since you're already aware of these pain points, I'm hoping that answering your questions here will help you to identify any other unforeseen issues.

> This integration seems to only deploy the static cached template files that it has generated. Any suggestions for how to deploy all of the other files – CSS, JS, images, etc – needed by the site?

Make sure you are on at least version 3.0.0-RC2 and use the `Commands Before` setting to copy your files and folders to the Git repo, for example:
```
cp -r ~/dynamic-site/web/assets ~/static-repo/assets;
cp -r ~/dynamic-site/web/interface ~/static-repo/interface;
```

> Since Blitz is operating on its own server, all of the URLs it generates, caches, and deploys are based on the siteUrl for that Craft install. But the Netlify domain won't be the same, so I'm not sure how URLs are supposed to continue to work once deployed to Netlify.

Avoid using absolute URLs and instead use relative URIs wherever possible, including the base URL for your volumes. Rather than using `siteUrl` and `url()`, use `/` and `uri()`, for example:
```
<a href="/">Home</a>
<a href="/{{ entry.uri }}/">{{ entry.title }}</a>
```

> I currently use Asset Rev for revving static files (CSS + JS). But since Blitz isn't deploying the revved CSS + JS files that are on the main Craft server, or the manifest.json that contains the information for them, there's no obvious way to ensure that Netlify will include the files that the cached Blitz templates point to. This one isn't really Blitz's problem but it is a pain point.

Use the `Commands Before` setting as above:
```
cp ~/dynamic-site/web/manifest.json ~/static-repo/manifest.json;
```

> During development, it isn't really an issue that my Craft install is at https://foo.com and Netlify deploy is at https://foo.netlify.com, but what is the recommended setup for this in production? Would you suggest a setup like https://admin.foo.com for Craft and https://foo.com for the Netlify deployment?

I tend to use `https://cms.foo.com` for Craft and `https://www.foo.com` for Netlify, because [yes-www.org](https://www.yes-www.org/why-use-www/).

**Comment by cmalven** [comment]
You're an amazing human being @bencroker 

Thank you so much. This all makes perfect sense and I'll give it a shot as soon as I get the chance and report back.

**Comment by cmalven** [comment]
@bencroker I just updated to `3.0.0-RC2` but I'm still not seeing a `Commands Before` setting. A Github search in the `blitz` repo for `Commands Before` in the code didn't turn up anything, either. Where should I be looking for this?

**Comment by bencroker** [comment]
It should appear at the bottom of the `Remote Deployment` tab in the plugin settings.

<img width="608" alt="Screenshot 2019-11-20 at 22 05 30" src="https://user-images.githubusercontent.com/57572400/69278110-f0940100-0be1-11ea-8948-2dea6c4d1372.png">

**Comment by bencroker** [comment]
Apologies Chris, I just noticed that this is the Blitz **Netlify deployer**. For the settings above, use the **Git deployer** (which is regardless the way I would recommend deploying to Netlify).

**Comment by cmalven** [comment]
Ahhhhh… That makes sense. I decided to try the **Netlify Deployer** because I thought it might avoid the need to create a separate repo dedicated to the static site, but no worries, I'll give that a shot.

**Comment by bencroker** [comment]
While the setup is easier, the Netlify deployer needs to zip the files and upload them all to Netlify which can understandably be a rather slow process. Using the Git deployer, while requiring a bit more setup, will ensure that only modified files are uploaded, which is why it is recommended for assets and other static files. I'll make a note in the docs as I understand that this could be confusing.

**Comment by cmalven** [comment]
@bencroker Got everything working on this site with your tips. Pretty slick. Amazing to have the option of getting the best of the Craft editing and templating experience with the performance and scalability of static deploys.

> Avoid using absolute URLs and instead use relative URIs wherever possible, including the base URL for your volumes. Rather than using siteUrl and url(), use / and uri()

That makes sense. The only place I can't easily apply this on my current site are in the URLs generated by SEOmatic – e.g. `<link href="//foo.com/blog" rel="canonical">`

**Comment by putyourlightson** [comment]
@cmalven Yes the site URL is something that still needs to be worked around. In the case of SEOmatic, a new config setting, `siteUrlOverride`, was recently added that allows you, as the name suggests, to override the site URL to anything you want.
https://github.com/nystudio107/craft-seomatic/commit/67442bfd2e207875cf149072bcf0b365a4a02c57

**Comment by bencroker** [comment]
@cmalven Yes the site URL is something that still needs to be worked around. In the case of SEOmatic, a new config setting, `siteUrlOverride`, was recently added that allows you, as the name suggests, to override the site URL to anything you want.
https://github.com/nystudio107/craft-seomatic/commit/67442bfd2e207875cf149072bcf0b365a4a02c57

**Comment by cmalven** [comment]
@bencroker Thanks I didn't realize that `siteUrlOverride` config item existed. Would be nice if there was a way to set this override before Git deployment, and then reset the value after deployment. As it stands, this is the only place I've found where the site can't operate both via Netlify _and_ as a standard server-based Craft site without changing any config that would result in one of them affecting the other. I suppose I could use the `Commands Before` and `Commands After` options in Blitz to set this SEOmatic as an environment variable only for deploy.
